name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-nix
        with:
          cache-key-name: lint

      - name: Run repository checks
        run: nix develop --command prek -a

  nix-build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-nix
        with:
          cache-key-name: nix-build

      - name: Build package
        run: nix build --no-link .#trees --print-build-logs

      - name: Check Flake
        run: nix flake check --no-build
